export const rows1=[
    "",
    "Totales",
    "",
    "Creditos Fiscales en Bolivar",
    "DE=Deducibles PD=Parcialmente Deducidas ND=No Deducibles",
    "",
    "Total de las compras de importacion afectadas sólo en alicuota general",
    "Total de las compras de importacion afectadas  en alicuota general + Adicional",
    "Total de las compras de importacion Exentas/Exoneradas",
    "Total de las compras internas afectadas solo en alicuota general",
    "Total de las compras internas afectadas en alicuota general + Adicional",
    "Total de las compras internas afectadas solo en alicuota general",
    "Total de las compras de internas afectadas en alicuota reducida",
    "Total de las compras Externas Internas",
    "Total de las compras Exoneradas",
    "Total de las compras no sujetas",
    "Total de las compras de las compras Sin derecho a Credito",
    "Total de las compras Externas Internas",
    "Total General",
    "Creditos Fiscales Totalmente deducible",
    "Creditos Fiscales Parcialmente deducible",
    "Creditos Fiscales Totalmente deducidas",
    
    "Total Creditos Fiscales Deducibles",
    "",
    "***Totales sin Centimos***",
    "Total de las compras de importacion afectadas sólo en alicuota general",
    "Total de las compras de importacion afectadas  en alicuota general + Adicional",
    "Total de las compras de importacion Exentas/Exoneradas",
    "Total de las compras internas afectadas solo en alicuota general",
    "Total de las compras internas afectadas en alicuota general + Adicional",
    "Total de las compras internas afectadas solo en alicuota general",
    "Total de las compras de internas afectadas en alicuota reducida",
    "Total de las compras Externas Internas",
    "Total de las compras Exoneradas",
    "Total de las compras no sujetas",
    "Total de las compras de las compras Sin derecho a Credito",
    "Total de las compras Externas Internas",
    "Total General",
    "Creditos Fiscales Totalmente deducible",
    "Creditos Fiscales Parcialmente deducible",
    "Total Creditos Fiscales Deducibles",
    "Ajuste a los creditos fiscales de periodos anteriores"
]
export const rows2="Base Imponible"
export const rows3="Credito Fiscal"
